#!/usr/bin/env bash
# scripts/access-review.sh
#
# Generates a quarterly access review report for all IAM roles
# managed by this GitOps pipeline.
#
# NIST 800-53: AC-2(3) — Disable Accounts / Periodic Review
#
# Output: Markdown report listing all roles, last-used dates,
# attached policies, and whether they require re-certification.
#
# Usage:
#   ./scripts/access-review.sh [--output report.md] [--days-threshold 90]

set -euo pipefail

# -------------------------------------------------------
# Configuration
# -------------------------------------------------------
OUTPUT_FILE="${1:---output}"
if [[ "$OUTPUT_FILE" == "--output" ]]; then
  OUTPUT_ARG="${2:-access-review-$(date +%Y-%m-%d).md}"
  OUTPUT_FILE="$OUTPUT_ARG"
fi

DAYS_THRESHOLD="${DAYS_THRESHOLD:-90}"  # flag roles unused for > 90 days
REPO_TAG_VALUE="gitops-iam"             # only review roles managed by this repo
REPORT_DATE=$(date -u +"%Y-%m-%d")
REPORT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "Generating IAM access review report..."
echo "Report date: $REPORT_DATE"
echo "Flagging roles unused for > $DAYS_THRESHOLD days"
echo ""

# -------------------------------------------------------
# Fetch all IAM roles managed by this repo
# -------------------------------------------------------
ROLES=$(aws iam list-roles \
  --query "Roles[?Tags[?Key=='Repository' && Value=='$REPO_TAG_VALUE']].RoleName" \
  --output json)

ROLE_COUNT=$(echo "$ROLES" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
echo "Found $ROLE_COUNT roles tagged Repository=$REPO_TAG_VALUE"

# -------------------------------------------------------
# Build the report
# -------------------------------------------------------
{
  echo "# IAM Access Review Report"
  echo ""
  echo "**Report Date:** $REPORT_DATE"
  echo "**Generated by:** scripts/access-review.sh"
  echo "**Scope:** All IAM roles tagged \`Repository=gitops-iam\`"
  echo "**Review period:** Previous 90 days"
  echo "**NIST control:** AC-2(3) — Periodic Account Review"
  echo ""
  echo "---"
  echo ""
  echo "## Summary"
  echo ""
  echo "| Metric | Count |"
  echo "|---|---|"

  TOTAL=0
  STALE=0
  ACTIVE=0

  declare -a ROLE_DATA=()

  while IFS= read -r ROLE_NAME; do
    ROLE_NAME=$(echo "$ROLE_NAME" | tr -d '"')
    [[ -z "$ROLE_NAME" ]] && continue

    TOTAL=$((TOTAL + 1))

    # Get role details
    ROLE_INFO=$(aws iam get-role --role-name "$ROLE_NAME" --output json 2>/dev/null || echo "{}")
    DESCRIPTION=$(echo "$ROLE_INFO" | python3 -c "import json,sys; r=json.load(sys.stdin); print(r.get('Role',{}).get('Description','No description'))" 2>/dev/null || echo "N/A")
    CREATED=$(echo "$ROLE_INFO" | python3 -c "import json,sys; r=json.load(sys.stdin); print(r.get('Role',{}).get('CreateDate','Unknown')[:10])" 2>/dev/null || echo "Unknown")
    OWNER=$(echo "$ROLE_INFO" | python3 -c "
import json,sys
r=json.load(sys.stdin).get('Role',{})
tags={t['Key']:t['Value'] for t in r.get('Tags',[])}
print(tags.get('Owner','Unknown'))
" 2>/dev/null || echo "Unknown")

    # Get last used date
    LAST_USED=$(aws iam get-role --role-name "$ROLE_NAME" \
      --query "Role.RoleLastUsed.LastUsedDate" \
      --output text 2>/dev/null || echo "None")

    if [[ "$LAST_USED" == "None" || "$LAST_USED" == "null" ]]; then
      LAST_USED_DISPLAY="Never used"
      DAYS_SINCE=999
      STATUS="⚠️ NEVER USED"
    else
      LAST_USED_DISPLAY="${LAST_USED:0:10}"
      DAYS_SINCE=$(python3 -c "
from datetime import datetime, timezone
last = datetime.fromisoformat('${LAST_USED_DISPLAY}')
now = datetime.now()
print((now - last).days)
" 2>/dev/null || echo "0")
    fi

    if [[ "$DAYS_SINCE" -gt "$DAYS_THRESHOLD" ]]; then
      STALE=$((STALE + 1))
      STATUS="⚠️ STALE (${DAYS_SINCE}d)"
    else
      ACTIVE=$((ACTIVE + 1))
      STATUS="✅ Active"
    fi

    # Get attached policies
    POLICIES=$(aws iam list-attached-role-policies \
      --role-name "$ROLE_NAME" \
      --query "AttachedPolicies[].PolicyName" \
      --output json 2>/dev/null | python3 -c "import json,sys; print(', '.join(json.load(sys.stdin)))" 2>/dev/null || echo "None")

    ROLE_DATA+=("$ROLE_NAME|$OWNER|$CREATED|$LAST_USED_DISPLAY|$STATUS|$POLICIES|$DESCRIPTION")

  done < <(echo "$ROLES" | python3 -c "import json,sys; [print(r) for r in json.load(sys.stdin)]")

  echo "| Total roles | $TOTAL |"
  echo "| Active (used within ${DAYS_THRESHOLD}d) | $ACTIVE |"
  echo "| Stale / never used | $STALE |"
  echo ""
  echo "---"
  echo ""
  echo "## Role Inventory"
  echo ""
  echo "| Role Name | Owner | Created | Last Used | Status | Attached Policies |"
  echo "|---|---|---|---|---|---|"

  for ENTRY in "${ROLE_DATA[@]}"; do
    IFS='|' read -r NAME OWNER CREATED LAST_USED STATUS POLICIES DESC <<< "$ENTRY"
    echo "| \`$NAME\` | $OWNER | $CREATED | $LAST_USED | $STATUS | $POLICIES |"
  done

  echo ""
  echo "---"
  echo ""
  echo "## Certifier Actions Required"
  echo ""
  echo "For each role listed as ⚠️ STALE or ⚠️ NEVER USED, the Owner team must:"
  echo ""
  echo "1. Confirm whether the role is still required"
  echo "2. If required: document the business justification in a PR comment"
  echo "3. If not required: open a PR to remove the role from Terraform"
  echo "4. All certifications must be completed within 30 days of this report"
  echo ""
  echo "---"
  echo ""
  echo "## Audit Trail"
  echo ""
  echo "This report was generated at \`$REPORT_TIMESTAMP\`."
  echo "Store this file in the \`docs/access-reviews/\` directory and commit it to Git."
  echo "The commit hash serves as the audit record for this review cycle."
  echo ""
  echo "_NIST SP 800-53 AC-2(3): The organization reviews accounts for compliance with account management requirements at a frequency defined by the organization._"

} > "$OUTPUT_FILE"

echo ""
echo "Report written to: $OUTPUT_FILE"
echo "Total: $TOTAL | Active: $ACTIVE | Stale: $STALE"
echo ""
echo "Next step: commit this report to docs/access-reviews/ as your AC-2(3) audit evidence."
